{% set name = "opentelemetry-instrumentation-weaviate" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 27226bb6ec801f5ccbac331b8265d425b4a8b6f2af2342a1f8197a37c2adf7e8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
  run_constrained:
    - weaviate-client >=3.26,<4.0

# Unable to run tests, weaviate-client is not in the main channel.
test:
  imports:
    - opentelemetry.instrumentation.weaviate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Weaviate instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing client-side calls to Weaviate vector DB sent with the official Weaviate library.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
